config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  root 'pages#index'

  get 'pages/location'

  get 'pages/faq'

  get 'pages/news'

  get 'pages/music'

  get 'pages/activities'

  get 'pages/gallery'

  get 'pages/food'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'items/:id/add' => 'items#add_quantity', as: 'item_add'
  post 'items/:id/reduce' => 'items#reduce_quantity', as: 'item_reduce'
  post 'items' => 'items#create'
  get 'items/:id' => 'items#show', as: 'item'
  delete 'items/:id' => 'items#destroy', as: 'item_delete'

  resources :products, :orders, :pages

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  tax        :decimal(, )      default("0.1")
#  shipping   :decimal(, )      default("0")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
  has_many :items, -> { order 'created_at asc'}
    has_many :products, through: :items


    # LOGIC
  def subtotal
    sum = 0

    items.each do |item|
      sum += item.subtotal
    end

    sum
  end

  def total
    subtotal + (subtotal * tax) + shipping
  end

  def total_quantity
    sum = 0
    items.each do |item|
      sum += item.quantity
    end
    sum
  end

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id                  :integer          not null, primary key
#  quantity            :integer          default("0")
#  product_id          :integer
#  cart_id             :integer
#  order_id            :integer
#  historical_price    :integer
#  historical_quantity :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Item < ActiveRecord::Base
    belongs_to :product
    belongs_to :cart
    belongs_to :order

    def subtotal
      self.product.price * self.quantity
    end
    
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  name       :string
#  address1   :text
#  status     :string           default("in progress")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base
  has_many :items, dependent: :destroy

  def subtotal
        sum = 0

        items.each do |item|
          sum += item.subtotal
        end

        sum
      end
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer          not null, primary key
#  product_name  :string
#  product_desc1 :text
#  product_desc2 :text
#  price         :decimal(, )
#  active        :boolean          default("true")
#  brand_id      :integer
#  image         :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Product < ActiveRecord::Base
has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_cart
    before_action :fetch_order

    def order_quantity
    @current_order.items.each do |item|
      @sum = 0
    order_quantity =  item.quantity
    @sum += item.quantity
  end
end

  private
    # Create new empty cart when new user visits
    def current_cart
      if session[:cart_id]
        cart = Cart.find_by(:id => session[:cart_id])
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id] == nil
        @current_cart = Cart.create
        session[:cart_id] = @current_cart.id
      end
    end

    def fetch_order
        @current_order = Order.find_by(:id => session[:order_id]) if session[:order_id]

        session[:order_id] = nil unless @current_order.present?
      end

  end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart

    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart
    if current_cart.products.include?(chosen_product)
      # We want to find the item with that product and increment its quantity by one
      @item = current_cart.items.find_by(product_id: chosen_product)
      @item.quantity += 1
    else
      @item = Item.new # Instantiating a new Item class
      @item.cart = current_cart # Append the @current_cart from the session to the item's belongs_to cart relationship
      @item.quantity = 1
      @item.product = chosen_product
      @item.historical_price = chosen_product.price
      @item.historical_quantity = @item.quantity
    end
    @item.save
    redirect_to cart_path(current_cart)
  end

  def add_quantity
    @item = Item.find(params[:id])
    @item.quantity += 1
    @item.save
    redirect_to cart_path(@current_cart)
    end

  def reduce_quantity
    @item = Item.find(params[:id])
    @item.quantity -= 1 if @item.quantity > 1
    @item.save
    redirect_to cart_path(@current_cart)
end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to cart_path(@current_cart)
    end

  private

  def item_params
    params.require(:item).permit(:product_id, :cart_id, :order_id, :quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @cart = @current_cart
  end

  def create
      @order = Order.new(order_params)
      # We want to pass in all the cart items to the order model
      @current_cart.items.each do |item|
        @order.items << item
        # item.cart_id = nil
      end

      @order.save
      # Store the order id in a session
      session[:order_id] = @order.id if @order.save
      # Cart.destroy(session[:cart_id])
      # session[:cart_id] = nil

      redirect_to orders_path
    end


  # def create
  #     items = @current_cart.items
  #     @order = Order.new
  #     items.each do |item|
  #       @order.items << item
  #       item.cart_id = nil
  #     end
  #
  #     if @order.save
  #       session[:order_id] = @order.id
  #     end
  #     redirect_to orders_path
  #   end

    def edit
      @order = Order.find(params[:id])
    end

    def show
      @order = Order.find(params[:id])
      @cart = @current_cart
    end

    def update
      @order = Order.find(params[:id])
      @order.update(order_params)
      @order.save
      redirect_to orders_path
    end

    def destroy
      @order = Order.find(params[:id])
      @order.destroy
      redirect_to orders_path
    end

    private

    def order_params
      params.require(:order).permit(:name, :address1, :status)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def location
  end

  def faq
  end

  def news
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all

  end

  def new
      @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
    end

  private

  def product_params
    params.require(:product).permit(:product_name, :product_desc1, :product_desc2, :price, :active, :image, :brand_id)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/carts/show.html.erb
<h1>Current Cart</h1>

<!-- <p>Cart ID:
    <%#= @cart.id %></p> -->
<hr>

<% if @cart.items.length > 0  %>
<% @cart.items.each do |item| %>
<ul>

    <li class="cart">Product:
        <%= item.product.product_name %></li>
    <li class="cart">Price:
        <%=number_to_currency(item.product.price)%></li>
    <li class="cart">Quantity:
        <%= item.quantity %></li>
    <!-- <li>Product ID:
        <%#= item.product_id %></li> -->
<br>
    <li class="cart"><%= link_to "+", item_add_path(:id => item), method: :post, :class=>"main-list cart-1" %></li>
    <li><%= link_to "-", item_reduce_path(:id => item), method: :post, :class=>"main-list cart-1" %></li>
    <li><%= link_to "Remove", item_path(item), method: :delete, :class=>"main-list cart-1" %></li>
</ul>
<!--note there is no order id as order has not been created yet - just items in a shopping cart  -->
<!-- <li>Historical Price <%=item.historical_price %></li>
      <li>Historical Quantity <%=item.historical_quantity %></li> -->
<% end %>
<ul>
    <p>Total to Pay:
        <%= number_to_currency(@cart.subtotal) %></p>
</ul>
<br>
<br>
<%#= link_to "Confirm Order", new_order_path, :class=>"btn-buy" %>
<br>
<br>
<ul>
    <li>
    <%= button_to "Checkout", new_order_path, method: :get, :class=>"btn-shop" %>
</li>
    <li>
        <%= button_to "Continue Shopping", products_path, method: :get, class: 'btn-shop' %>
    </li>
    <li>
        <%= button_to "Empty cart", cart_path(@cart), method: :delete, data: {confirm: "Are you sure you want to empty your cart?"}, class: 'btn-shop' %>
    </li>
</ul>

<br>
<div class="footer-push">
</div>

</div>

</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Festival De Musica</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="//fonts.googleapis.com/css?family=Lato|Luckiest+Guy" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB8pkihkQzjK5a-xn8TcJOtI4khAs0UVp8&callback=initMap"
  async defer>
</script>

    </head>
    <body>

        <nav>
            <div class="stylenav grad">
                <ul class="navbar" id="myNavBar">
            <li>
                <%= link_to("HOME", pages_index_path) %>
            </li>
            <li>
                <%= link_to("BUY TICKETS", products_path) %>
            </li>
            <li>
                <%= link_to("MUSIC", pages_music_path) %>
            </li>
            <li>
                <%= link_to("FOOD", pages_food_path) %>
            </li>
            <li>
                <%= link_to("ACTIVITIES", pages_activities_path) %>
            </li>
            <li>
                <%= link_to("FAQ", pages_faq_path) %>
            </li>
            <li>
                <%= link_to("LOCATION", pages_location_path) %>
            </li>
            <li class="icon">
                <a href="javascript:void(0);" onclick="navBarFunction()">&#9776;</a>
            </li>
</ul>
        </div>

    </nav>

    <%= yield %>

<footer>
  </div>
<div class="main-foot">

    <h3>FESTIVAL DE MUSICA AT BOOGALOO</h3>
    <h3>1 APRIL 2018</h3>

    <div class="footer-links">

      <li>
          <%= link_to("HOME", pages_index_path) %>
      </li>
      <li>
          <%= link_to("BUY TICKETS", products_path) %>
      </li>
      <li>
          <%= link_to("MUSIC", pages_music_path) %>
      </li>
      <li>
          <%= link_to("FOOD", pages_food_path) %>
      </li>
      <li>
          <%= link_to("ACTIVITIES", pages_activities_path) %>
      </li>
      <li>
          <%= link_to("FAQ", pages_faq_path) %>
      </li>
      <li>
          <%= link_to("LOCATION", pages_location_path) %>
      </li>

  </ul>
    <p>Website designed by Steve Gibbs</p>

</div>


  </footer>

</body>
</html>

app/views/orders/_form.html.erb
<%=form_for @order do |f| %>


<span>Name</span>
<%= f.text_field :name, :required => true, :autofocus => true %>
    <span>Address</span>
<%= f.text_field :address1, :required => true %>
    <!-- <span>Order Status</span> -->
<%#= f.select :status,["in progress","Paid","Shipped"] %>

        <%= f.submit "Checkout", :class=> "btn-buy"%>
        <% end %>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= render "form" %>

app/views/orders/index.html.erb
<h1>Orders</h1>


<% @orders.each do |order| %>
    <ul>
    <li>Name: <%= order.name %></li>
      <li>Address: <%= order.address1 %></li>
      <li>Status: <%= order.status %></li>
      <li>Items: </li>
        <% order.items.each do |item| %>
            <li>Product:
                <%= item.product.product_name %>;
                Quantity:
                <%= item.quantity %>;
            Product Price: <%= item.product.price %>
            <li>Total: <%=item.subtotal %></li>
            </li>
        <% end %>
      </ul>
    </ul>
<% end %>

app/views/orders/new.html.erb
<h1>Your Order Details</h1>


<% @cart.items.each do |item| %>

<ul>
    <li class="cart">Product:
        <%= item.product.product_name %></li>
    <li class="cart">Price:
        <%= number_to_currency(item.product.price) %></li>
    <li class="cart">Quantity:
        <%= item.quantity %></li>
</ul>
<% end %>

<h4>Subtotal:
    <%= number_to_currency(@cart.subtotal) %></h4>
<h4>GST (10%):
    <%= number_to_currency(@cart.tax * @cart.subtotal) %></h4>
<h4>Shipping:
    <%= number_to_currency(@cart.shipping) %></h4>
<h3>TOTAL:
    <%= number_to_currency(@cart.total) %></h3>


<br>
<hr>
<br>



  <h3>Add My Details</h3>

  <fieldset>
      <legend>Enter payment details</legend>

      <%= render "form" %>
  </fieldset>
<br>
<br>
<br>
<div class="footer-push">

</div>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/pages/activities.html.erb
<h1 class="banner">FESTIVAL DE MUSICA</h1>
<h3 class="second-banner">ACTIVITIES</h3>

<br>
<br>
<br>
<%= image_tag("meditation.jpg", :class => "main-image") %>
<br>
<br>
<br>


    <p class="main-text">YOGA</p>
    <p class="location">Starting at 11am and then on the hour until 4pm, each 40 minute yoga session is guaranteed to loosen you up, free your mind of worries and allow you to enjoy the ambience of the festival.  Our instructors are fully accredited and there is room for 40 mats (provided) at each session.</p>
    <br>
    <br>
    <br>
    <%= image_tag("groupdance.jpg", :class => "main-image") %>
    <br>
    <br>
    <br>


        <p class="main-text">GROUP DANCE</p>
        <p class="location">Starting at 11am and then every half hour until 4pm, we will hold a 20 minute group dance session for 100 people to the classic hits likely to be played at the festival.  We then hope to have some synchronised dancing during the performances.</p>
        <br>
        <br>
        <br>
        <%= image_tag("garland2.jpg", :class => "main-image") %>
        <br>
        <br>
        <br>
        </div>

        <p class="main-text">HAIR BRAIDING AND GARLANDS</p>
        <p class="location">Visit the Flower Power stand to enjoy a complimentary floral garland.</p>
        <br>
        <br>
        <br>

app/views/pages/faq.html.erb
<!-- add collapsible list here -->
<!-- what to bring, weather, food and drink, forbidden, disabled access, conditions of entry, public transport, car -->

<h2>FREQUENTLY ASKED QUESTIONS</h2>

<h4>GENERAL INFORMATION</h4>

<button class="accordion">WHAT TO BRING</button>
<div class="panel">
  <p class="panel-style">Raincoats in case of rain (no umbrellas are allowed), picnic rugs, small foldable chairs and picnic hampers.</p>
</div>

<button class="accordion">WEATHER</button>
<div class="panel">
<p class="panel-style">The festival will still be held, even in heavy rain.  The festival will only be cancelled in the event of an electrical storm.</p>
</div>

<button class="accordion">FOOD AND DRINK</button>
<div class="panel">
  <p class="panel-style">You are welcome to bring your own food.  There will be many catering stalls on-site and free water refill stations.  No alcohol may be brought and will instead be available for purchase from any of the 8 bars located around the festival area.</p>
</div>

<button class="accordion">FORBIDDEN</button>
<div class="panel">
  <p class="panel-style">Alcohol may not be brought to the festival site.  Metal cutlery and umbrellas also may not be brought.</p>
</div>

<button class="accordion">DISABLED ACCESS</button>
<div class="panel">
  <p class="panel-style">There will be ramps for disabled viewing areas and disabled access toilets.</p>
</div>

<button class="accordion">CONDITIONS OF ENTRY</button>
<div class="panel">
  <p class="panel-style">Consumer laws apply.  We have the right to refuse entry if you do not adhere to the conditions outlined on your ticket or act in an offensive manner.  Passouts will be available on the day.  Bags are subject to a security search on entry.</p>
</div>

<button class="accordion">TRANSPORT</button>
<div class="panel">
  <p class="panel-style">There are trains on the Northern Line to Boogaloo Village.  Shuttle buses will operate to the festival site every 30mins from 9am until 3pm.  </p>

  <p class="panel-style">Boogaloo Forest can be reached on Davidson Road from the M1 if you are arriving by car.  Car parking facilities will be available for 1200 vehicles.</p>
</div>

<br>
<h4>TICKETING</h4>

<button class="accordion">ARE THERE TICKETS AT THE GATE?</button>
<div class="panel">
  <p class="panel-style">We will make available 400 tickets at the gate for casual entry, and any tickets left unsold beforehand.</p>
</div>

<button class="accordion">REFUNDS</button>
<div class="panel">
<p class="panel-style">Unfortunately no refunds are available once tickets are purchased, except in the event of a weather cancellation or cancellation of the event itself.  Management reserves the right to substitute artists of a comparable quality (decided at management's discretion) should an act be unavailable.</p>
</div>

<button class="accordion">CUSTOMER HOTLINE</button>
<div class="panel">
  <p class="panel-style">For technical issues with printing or receipt of your electronic ticket please call 1800 000 000 during office hours 9am to 5pm.</p>
</div>

app/views/pages/food.html.erb
<h1 class="banner">FESTIVAL DE MUSICA</h1>
<h3 class="second-banner">FOOD GLORIOUS FOOD</h3>

<div class="main-text2">
    <p class="main-text">STALLS</p>
    <p>Some of Melbourne's and Sydney's best known Food Trucks will making a visit to Boogaloo.  Cuisine from Asia, South America, America and Australia will be featured by Tacorama Truck, Viet Man and his Van, Mucho Sombrero, Won Ton To Go, The Brunch Bus and the Baguette Bros.
    </p>
    <p>Vegetarian, gluten free and allergen free options will be available.</p>

</div>
<div class="gallery">
    <%= image_tag("foodtruck.jpg", :class => "autoplay") %>
</div>

<div class="main-text2">
    <p class="main-text">HAMPERS</p>
    <p>Gourmet Hampers are available to be pre-purchased for collection at the Festival.
    </p>
    <p>Food and drinks will be available fresh and cold from the main collection point between 10am and 2pm.
    </p>
    <p>Please have your receipt ready.</p>
</div>

<div class="gallery">
    <%= image_tag("hamper1.jpg", :class => "autoplay") %>
</div>
<p class="main-text">THE CLASSIC PLOUGHMANS</p>
<p>Designed for two. Two baguettes with an assortment of accompaniments</p>
<p>100 grams each of leg ham, saucisson and country pate</p>
<p>100 grams each of Cheshire cheese, Brie and Rocquefort
</p>
<p>Two tomatoes, one cucumber, red oak lettuce</p>
<p>Quince paste and vinaigrette sauce</p>

<div class="gallery">
    <%= image_tag("sushi2.jpg", :class => "autoplay") %>
</div>
<p class="main-text">THE SAMURAI</p>
<p>Designed for two. A platter of assorted sushi and sashimi</p>
<p>6 sashimi pieces of tuna, salmon and kingfish</p>
<p>18 assorted sushi - 6 nigiri (fish on top of rice), 6 maki (seaweed wrapped) and 6 uramaki (rice on outside) of salmon, prawn, tuna, kingfish, eel and chicken</p>
<p>Ginger, wasabi and soy sauce and chopsticks</p>

app/views/pages/gallery.html.erb
<h1 class="banner">FESTIVAL DE MUSICA</h1>
<h3 class="second-banner">GALLERY OF PAST FESTIVALS</h3>


<div class="gallery">
    <div class="autoplay">

        <div>
            <%= image_tag("concert.jpg", :class => "autoplay") %>
        </div>
        <div>
            <%= image_tag("concert2.jpg", :class => "autoplay") %>
        </div>

        <div>
            <%= image_tag("concert3.jpg", :class => "autoplay") %>
        </div>
        <div>
            <%= image_tag("balloon.jpg", :class => "autoplay") %>
        </div>
        <div>
            <%= image_tag("audience.jpg", :class => "autoplay") %>
        </div>

        </div>
</div>

app/views/pages/index.html.erb
<div class="main-page">
    <%= image_tag("girlsinfield.jpg", :class => "main-image") %>
    <text class="main-banner">FESTIVAL DE MUSICA
        <p class="main-banner">in the Boogaloo Mountains</p>
        <p class="main-banner">1 APRIL 2018</p>
    </text>
</div>
<br>
<br>
<div class="main-text">
    <p class="main-text">A CELEBRATION OF ECLECTIC MUSIC FROM SOME OF THE WORLD'S BEST ARTISTS. BRING YOUR FRIENDS AND FAMILY TO ONE OF THE MOST ATMOSPHERIC FESTIVALS HELD NEXT TO THE FAMOUS BOOGALOO RANGES.</p>
    <br>
    <%= image_tag("forest.jpg", :class => "secondary-image") %>
    <br>
    <br>
    <h1 class="banner">FESTIVAL DE MUSICA</h1>
    <h3 class="second-banner">An Autumnal Frolic of Music in the Wilds of the Australian Mountains</h3>
    <br>
    <br>
    <%= link_to("BUY TICKETS", products_path, :class=>"btn-buy") %>
    <br>
    <br>
    <ul class="main-list">

        <li class="main-page-list"><%= link_to("MUSIC", pages_music_path, :class=>"main-list") %>
            <br>
            <br>
            <%= image_tag("audience.jpg", :class => "tertiary-image") %>
            <br>
        </li>
        <li class="main-page-list"><%= link_to("ACTIVITIES", pages_activities_path, :class=>"main-list") %>
            <br>
            <br>
            <%= image_tag("festival.jpg", :class => "tertiary-image") %>
            <br></li>
        <li class="main-page-list"><%= link_to("FAQ", pages_faq_path, :class=>"main-list") %><br>
            <br>
            <%= image_tag("flowerchild.jpg", :class => "tertiary-image") %>
            <br>
        </li>
    </ul>
    <ul class="main-list">

        <li class="main-page-list"><%= link_to("GALLERY", pages_gallery_path, :class=>"main-list") %><br>
            <br>
            <%= image_tag("concert2.jpg", :class => "tertiary-image") %>
            <br>
        </li>
        <li class="main-page-list"><%= link_to("FOOD AND DRINK", pages_food_path, :class=>"main-list") %><br>
            <br>
            <%= image_tag("picnic.jpg", :class => "tertiary-image") %>
            <br>
        </li>
        <li class="main-page-list"><%= link_to("LOCATION", pages_location_path, :class=>"main-list") %>
            <br>
            <br>
            <%= image_tag("balloon.jpg", :class => "tertiary-image") %>
            <br>
        </li>
    </ul>

    <div class="sponsors">
        <h3 class="sponsors-text">SPONSOR BANNER HERE</h3>
    </div>

</div>
<br>
<br>

app/views/pages/location.html.erb
<h1 class="banner">BOOGALOO FESTIVAL DIRECTIONS</h1>
<p></p>
<br>

<div id="map"></div>
<br>
<p class="location">Boogaloo Festival is located one kilometre inside the entrance to Dharawal National Park.  If driving, from the M1, please turn onto B69, then onto the 106 Trail Road (unsealed) through the park entrance.  Festival tickets include the entrance fee to the National Park.  There will be be ample signposting inside the park and wardens who will then direct you to the four parking areas.</p>
<p class="location">Alternatively there are free shuttle buses from Thirroul town centre leaving each 30mins from 9am until 3pm.</p>

app/views/pages/music.html.erb
<h1 class="banner">FESTIVAL DE MUSICA</h1>
<h3 class="second-banner">ORDER OF PLAY</h3>

<br>
<br>
<br>
<%= image_tag("concert.jpg", :class => "main-image") %>
<br>
<br>
<br>


    <p class="main-text">JIMMY FREEDOM AND HIS FREEDOM FIGHTERS - 9AM</p>
    <p>Fresh from his South American tour, Jimmy will electrify the stage with his four piece band, the Freedom Fighters.  Known for his energetic stage presence, Jimmy will bring the house down with new interpretations of his famous back catalogue.</p>
    <br>
    <br>
    <br>
    <%= image_tag("concert2.jpg", :class => "main-image") %>
    <br>
    <br>
    <br>


        <p class="main-text">ELECTRONICA ALERT - 11AM</p>
        <p>Boasting a rotating 16 musician strong group, Electronica Alert, stays at the forefront of groundbreaking sounds.  Let them take you on a journey from a more soulful ambience to a wild and whooping jungle menagerie.</p>
        <br>
        <br>
        <br>
        <br>
        <%= image_tag("concert3.jpg", :class => "main-image") %>
        <br>
        <br>
        <br>

    
            <p class="main-text">TOM THE GUN - 1PM</p>
            <p>Tom the Gun never fails to please.  Mixing the drawl of Minnesota with new wave beat boy, Tom is guaranteed to delight audiences. </p>
            <br>

app/views/pages/news.html.erb
<h1>Pages#news</h1>
<p>Find me in app/views/pages/news.html.erb</p>

app/views/products/_form.html.erb
<%= form_for @product do |item| %>

<p>Product Name</p>
<%=item.text_field :product_name, :required => true %>
<p>Product Description</p>
<%=item.text_area :product_desc1, :required => true %>
<p>Additional Description</p>
<%=item.text_area :product_desc2, :required => true %>
<p>Price</p>
<%=item.number_field :price, :required => true %>
<p>Image</p>
<%=item.text_field :image, :required => true %>
<p>Brand</p>
<%=item.text_field :brand_id, :required => true %>
<%= item.submit "Submit", :class=> "submit_format" %>
<%end%>

app/views/products/edit.html.erb
<h1>Edit
    <%= @product.product_name %></h1>

<%= render "form" %>

app/views/products/index.html.erb
<h1>TICKET PURCHASE PAGE UNDER CONSTRUCTION</h1>

<% @products.each do |item| %>
<span class="ticket-heading"><%=item.product_name%></span>
<br>
<br>
<%=item.product_desc1%>
<br>
<%=number_to_currency(item.price, :precision => 0)%>
<ul class="product-buy">
  <li>
    <%=button_to "Buy", items_path(:product_id => item.id), :class=>"product-buy"%>
  </li>
  <li>
    <%= button_to "Admin Edit", edit_product_path(item), method: :get, :class=>"admin" %>
  </li>
</ul>
<br>

<%end%>

app/views/products/new.html.erb
<%= render "form" %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>